export const REPORT_OPERATIONAL_STATUS = {
  NAO_INICIADO: 'NAO_INICIADO',
  EM_PLANEJAMENTO: 'EM_PLANEJAMENTO',
  EM_ANDAMENTO: 'EM_ANDAMENTO',
  EM_ELABORACAO: 'EM_ELABORACAO',
  EM_REVISAO: 'EM_REVISAO',
  AGUARDANDO_APROVACAO: 'AGUARDANDO_APROVACAO',
  BLOQUEADO: 'BLOQUEADO',
  ENTREGUE: 'ENTREGUE',
};

export const REPORT_SOURCE_OVERRIDE = {
  AUTO: 'AUTO',
  LO: 'LO',
  PROJECT: 'PROJECT',
};

const OPERATIONAL_STATUS_LABELS = {
  [REPORT_OPERATIONAL_STATUS.NAO_INICIADO]: 'Nao iniciado',
  [REPORT_OPERATIONAL_STATUS.EM_PLANEJAMENTO]: 'Planejamento',
  [REPORT_OPERATIONAL_STATUS.EM_ANDAMENTO]: 'Em andamento',
  [REPORT_OPERATIONAL_STATUS.EM_ELABORACAO]: 'Elaboracao',
  [REPORT_OPERATIONAL_STATUS.EM_REVISAO]: 'Revisao',
  [REPORT_OPERATIONAL_STATUS.AGUARDANDO_APROVACAO]: 'Aguardando aprovacao',
  [REPORT_OPERATIONAL_STATUS.BLOQUEADO]: 'Bloqueado',
  [REPORT_OPERATIONAL_STATUS.ENTREGUE]: 'Entregue',
};

const OPERATIONAL_STATUS_TONES = {
  [REPORT_OPERATIONAL_STATUS.NAO_INICIADO]: 'neutral',
  [REPORT_OPERATIONAL_STATUS.EM_PLANEJAMENTO]: 'warning',
  [REPORT_OPERATIONAL_STATUS.EM_ANDAMENTO]: 'warning',
  [REPORT_OPERATIONAL_STATUS.EM_ELABORACAO]: 'warning',
  [REPORT_OPERATIONAL_STATUS.EM_REVISAO]: 'critical',
  [REPORT_OPERATIONAL_STATUS.AGUARDANDO_APROVACAO]: 'critical',
  [REPORT_OPERATIONAL_STATUS.BLOQUEADO]: 'danger',
  [REPORT_OPERATIONAL_STATUS.ENTREGUE]: 'ok',
};

export const REPORT_OPERATIONAL_STATUS_OPTIONS = [
  {
    value: REPORT_OPERATIONAL_STATUS.NAO_INICIADO,
    label: OPERATIONAL_STATUS_LABELS[REPORT_OPERATIONAL_STATUS.NAO_INICIADO],
  },
  {
    value: REPORT_OPERATIONAL_STATUS.EM_PLANEJAMENTO,
    label: OPERATIONAL_STATUS_LABELS[REPORT_OPERATIONAL_STATUS.EM_PLANEJAMENTO],
  },
  {
    value: REPORT_OPERATIONAL_STATUS.EM_ANDAMENTO,
    label: OPERATIONAL_STATUS_LABELS[REPORT_OPERATIONAL_STATUS.EM_ANDAMENTO],
  },
  {
    value: REPORT_OPERATIONAL_STATUS.EM_ELABORACAO,
    label: OPERATIONAL_STATUS_LABELS[REPORT_OPERATIONAL_STATUS.EM_ELABORACAO],
  },
  {
    value: REPORT_OPERATIONAL_STATUS.EM_REVISAO,
    label: OPERATIONAL_STATUS_LABELS[REPORT_OPERATIONAL_STATUS.EM_REVISAO],
  },
  {
    value: REPORT_OPERATIONAL_STATUS.AGUARDANDO_APROVACAO,
    label: OPERATIONAL_STATUS_LABELS[REPORT_OPERATIONAL_STATUS.AGUARDANDO_APROVACAO],
  },
  {
    value: REPORT_OPERATIONAL_STATUS.BLOQUEADO,
    label: OPERATIONAL_STATUS_LABELS[REPORT_OPERATIONAL_STATUS.BLOQUEADO],
  },
  {
    value: REPORT_OPERATIONAL_STATUS.ENTREGUE,
    label: OPERATIONAL_STATUS_LABELS[REPORT_OPERATIONAL_STATUS.ENTREGUE],
  },
];

export function normalizeOperationalStatus(value) {
  const normalized = String(value || '').trim().toUpperCase();
  if (normalized in REPORT_OPERATIONAL_STATUS) return normalized;
  return REPORT_OPERATIONAL_STATUS.NAO_INICIADO;
}

export function normalizeSourceOverride(value) {
  const normalized = String(value || '').trim().toUpperCase();
  if (normalized in REPORT_SOURCE_OVERRIDE) return normalized;
  return REPORT_SOURCE_OVERRIDE.AUTO;
}

export function getOperationalStatusPresentation(status) {
  const normalized = normalizeOperationalStatus(status);
  return {
    value: normalized,
    label: OPERATIONAL_STATUS_LABELS[normalized] || OPERATIONAL_STATUS_LABELS.NAO_INICIADO,
    tone: OPERATIONAL_STATUS_TONES[normalized] || OPERATIONAL_STATUS_TONES.NAO_INICIADO,
  };
}

export function getSourceOverrideLabel(sourceOverride) {
  const normalized = normalizeSourceOverride(sourceOverride);
  if (normalized === REPORT_SOURCE_OVERRIDE.LO) return 'LO';
  if (normalized === REPORT_SOURCE_OVERRIDE.PROJECT) return 'Empreendimento';
  return 'Automatico';
}
